######################################################################
# Automatically generated by qmake (3.0) ?? 3? 16 21:32:46 2018
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Change
INCLUDEPATH += .

# Input
SOURCES += Change.cpp
