######################################################################
# Automatically generated by qmake (3.0) ?? 3? 16 21:04:11 2018
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Close
INCLUDEPATH += .

# Input
SOURCES += Close.cpp
