######################################################################
# Automatically generated by qmake (3.0) ?? 3? 20 21:22:30 2018
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Calculator
INCLUDEPATH += .

# Input
HEADERS += CalculatorDialog.h
SOURCES += CalculatorDialog.cpp main.cpp
