######################################################################
# Automatically generated by qmake (3.0) ?? 3? 20 22:14:30 2018
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Time
INCLUDEPATH += .

# Input
HEADERS += Time.h
SOURCES += main.cpp Time.cpp
