######################################################################
# Automatically generated by qmake (3.0) ?? 3? 16 18:48:01 2018
######################################################################
QT += widgets
TEMPLATE = app
TARGET = Button
INCLUDEPATH += .

# Input
SOURCES += main.cpp
